sudo: false
language: node_js
compiler:
  - gcc
  - clang
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 'stable'
  - v4
  - '0.12'
  - '0.10'
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
after_script:
  - npm run coveralls
