sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 'stable'
  - v4
  - '0.12'
  - '0.10'
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
after_script:
  - npm run coveralls
