sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - v4
  - v6
  - v8
before_script:
  - npm prune
after_success:
  - 'curl -Lo travis_after_all.py https://git.io/travis_after_all'
  - python travis_after_all.py
  - export $(cat .to_export_back) &> /dev/null
  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
after_script:
  - npm run coveralls
