language: node_js
notifications:
  email: false
node_js:
  - v8
  - v10
  - v12
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
jobs:
  include:
    - stage: release
      node_js: v12
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
after_script:
  - npm run coveralls
